KPI_LIST = [
    "Varianza de cronograma",
    "Indice de desempeño de cronograma",
    "Varianza de costo",
    "Indice de desempeño de costo",
    "% Alcance entregado según plan",
    "% Cambios de alcance aprobados",
    "% Entregables con aprobación formal",
    "Riesgos no identificados al inicio",
    "Indice de retrabajo, pruebas fallidas",
    "Presupuesto",
    "Valor planeado",
    "Valor ganado",
    "Costo real",
    "Velocidad del equipo",
    "Desviación de User Stories por iteración",
    "Cantidad de iteraciones completadas",
    "% Deuda técnica",
    "WIP promedio CFD",
    "Riesgos activos restantes",
    "Burn rate costo por SP entregado",
    "Indice de variación del Product Backlog",
    "% de entrega por iteración",
    "% tareas no funcionales en la iteración",
    "Story Points planificados vs entregados",
    "Lead time de punta a punta",
    "Tiempo de ciclo cycle time",
    "Work in Progress WIP promedio",
    "Throughput ítems completados por período",
    "% de retrabajo",
    "Tasa de defectos en producción",
    "% de tiempo de valor vs no valor",
    "Nivel de utilización de los recursos",
    "Número de bloqueos cuellos de botella",
    "Satisfacción del cliente Lean",
    "Throughput ítems completados por unidad de tiempo",
    "Cycle time promedio",
    "Lead time promedio",
    "Antigüedad de tarea Ageing histogram",
    "Work in Progress WIP por columna",
    "Classes of Service Expedite",
    "Classes of Service Fixed Date",
    "Classes of Service Standard",
    "Classes of Service Intangible",
    "% de features completadas por iteración",
    "Velocity story points por iteración",
    "% de defectos por feature",
    "Cobertura de pruebas test coverage",
    "Tiempo medio de integración continua CI",
    "% de tareas no funcionales por iteración",
    "Indice de variación del backlog",
    "% de deuda técnica reducida por iteración",
    "Lead time by feature",
    "Satisfacción de stakeholders por feature",
    "% de features completadas por iteración",
    "Cantidad de features por iteración",
    "% de deuda técnica por feature",
    "Lead time by feature",
    "Indice de variación del alcance en el model inventory",
    "Story points o días por feature",
    "% de tareas no funcionales por iteración",
    "Cumulative Flow Diagram CFD por feature",
    "% de defectos por feature",
    "Satisfacción de stakeholders por feature",
    "% de entregables Must Have completados por Timebox",
    "% de alcance Nice to Have diferido o cancelado",
    "Satisfacción del negocio por Timebox",
    "Nivel de participación activa del usuario final",
    "% de reuniones facilitadas sin retrasos",
    "% de cambios de prioridad en el backlog de Timebox",
    "% de entregas dentro del presupuesto previsto",
    "Número de requisitos no validados luego de la entrega",
    "Tiempo medio de respuesta a solicitudes de cambio",
    "% de calidad percibida por el usuario no solo defectos",
    "% de riesgos críticos resueltos por fase",
    "% de arquitectura estable establecida por fase",
    "Número de ítems de backlog refinados por fase",
    "% de iteraciones de construcción con entregas integradas",
    "Lead time por fase de inicio a fin de fase",
    "% de casos de prueba ejecutados por fase",
    "Satisfacción de stakeholders por fase",
    "% de deuda técnica registrada por fase",
    "Número de requisitos no claros o ambiguos en cada fase",
    "Indice de variación de alcance por fase",
    "Frecuencia de releases al usuario real",
    "Indice de comunicación osmótica del equipo",
    "% de miembros que reportan ambiente seguro para fallar",
    "% de iteraciones sin interrupciones externas mayores",
    "Frecuencia de acceso directo al usuario experto",
    "% de deuda técnica registrada por iteración",
    "% de retrabajo por iteración",
    "% de integration workshops realizados según plan",
    "Satisfacción de stakeholders por release",
    "% de acciones de retrospectiva implementadas",
    "% de entregas integradas por Sprint across teams",
    "% de dependencias de desarrollo resueltas entre equipos",
    "Número de ítems por Sprint tocados por múltiples equipos",
    "Lead time por Sprint para el mismo producto cross team",
    "% de requerimientos claros al inicio de Sprint",
    "Satisfacción de PO único por Sprint",
    "Número de incidencias de integración por Sprint",
    "% de refactorings o cambios de arquitectura compartida",
    "Coherencia de terminología y diseño entre equipos",
    "Indice de conflictos de prioridades entre equipos por Sprint",
    "% de adecuación del ciclo de vida elegido al contexto",
    "% de prácticas GCI adoptadas por el equipo",
    "% de decisiones basadas en goals DA vs reglas fijas",
    "Eficiencia del value stream tiempo valor vs total",
    "% de iteraciones con ajuste de proceso documentado",
    "% de deuda técnica registrada por iteración",
    "% de alineación con equipos enterprise HR Fin Ops",
    "Satisfacción de stakeholders por ciclo",
    "% de acciones de retrospectiva implementadas",
    "% de riesgos críticos resueltos por ciclo",
    "% de PI Objectives cumplidos por ART",
    "Número de dependencias resueltas antes del Sprint IP",
    "% de entregas integradas al final de cada PI",
    "Satisfacción del negocio con la PI Planning",
    "Tasa de cambios de prioridad en el backlog del PI",
    "% de tiempo del PI en features vs retrabajo incidentes",
    "Lead time from concept to cash por soluciones",
    "Número de innovaciones probadas en el Sprint IP",
    "% de competencias Lean Agile maduradas por PI",
    "Stakeholder Centricity Index CSI por PI",
    "% de hitos de fase cumplidos en fecha",
    "Indice de desempeño del cronograma SPI",
    "Indice de desempeño del costo CPI",
    "% de alcance macro congelado al cierre de diseño",
    "% de entrega por sprint dentro de cada fase",
    "% de checkpoints de fase aprobados sin retrabajo mayor",
    "% de retrabajo entre fases",
    "% de riesgos críticos resueltos por fase",
    "Satisfacción de stakeholders por checkpoint",
    "% de iteraciones ágiles alineadas al plan macro",
    "Indice de desempeño del cronograma SPI",
    "Indice de desempeño del costo CPI",
    "% de Stage Gates aprobados sin retrabajo mayor",
    "Velocity del equipo Scrum por sprint",
    "% de entrega por sprint",
    "% de entregables con aceptación formal del sponsor",
    "% de cambios de alcance procesados por control de cambios",
    "% de retrabajo por sprint",
    "% de decisiones PMO alineadas a cadencia Scrum",
    "Satisfacción de stakeholders por sprint review gate",
    "Lead time promedio",
    "Indice de desempeño del cronograma SPI",
    "Throughput ítems completados por semana",
    "WIP por columna vs límite planificado",
    "Antigüedad de tarea ítems mayor a umbral de tiempo",
    "Indice de desempeño del costo CPI",
    "% de retrabajo",
    "% de alcance macro estable post planificación",
    "% de ítems Kanban alineados al plan predictivo",
    "Satisfacción de stakeholders por revisión periódica",
    "% de stage boundaries aprobados sin excepciones",
    "% de entregables con aceptación formal documentada",
    "% de entrega por iteración ágil",
    "Velocity del equipo ágil por iteración",
    "% de riesgos críticos resueltos por stage",
    "% de retrabajo por iteración",
    "Indice de desempeño del cronograma SPI",
    "Indice de desempeño del costo CPI",
    "% de decisiones de proceso con trazabilidad PRINCE2",
    "Satisfacción de stakeholders por checkpoint de etapa",
    "Cobertura de pruebas automatizadas",
    "% de fases de verificación y validación completadas",
    "% de defectos detectados en testing vs producción",
    "% de retrabajo entre fases de validación",
    "% de iteraciones ágiles integradas al V Model",
    "Tiempo medio de integración continua CI",
    "% de riesgos técnicos resueltos por fase de validación",
    "Indice de desempeño del cronograma SPI",
    "% de requisitos con trazabilidad V Model iteración",
    "Satisfacción de stakeholders por fase de validación",
    "% de gates Go No Go aprobados sin retrabajo mayor",
    "ROI proyectado validado en cada gate",
    "% de entrega por sprint dentro del stage",
    "Velocity del equipo de desarrollo por sprint",
    "Lead time promedio entre gates consecutivos",
    "% de retrabajo detectado en gate review",
    "% de riesgos críticos resueltos antes de cada gate",
    "Indice de desempeño del costo CPI",
    "% de sprints alineados a criterios de éxito del gate",
    "Satisfacción de stakeholders por gate review",
]
